name: bandwhich
base: core22
adopt-info: bandwhich
summary: Terminal bandwidth utilization tool
description: 
  This is a CLI utility for displaying current network utilization by process,
  connection and remote IP/hostname

grade: stable
confinement: strict
parts:
  bandwhich:
    plugin: rust
    source: https://github.com/imsnif/bandwhich.git
    #source-tag: 0.20.0
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0).$(git rev-parse --short HEAD)
apps:
  bandwhich:
    command: bin/bandwhich
    plugs:
    - network
    - network-bind
    - network-control
    - network-status
    - system-observe
    - mount-observe
    - log-observe
