name: bandwhich
base: core22
version: "v1.11.0"
summary: Terminal bandwidth utilization tool
description: 
  This is a CLI utility for displaying current network utilization by process,
  connection and remote IP/hostname

grade: stable
confinement: strict
parts:
  bandwhich:
    plugin: rust
    source: https://github.com/imsnif/bandwhich.git
    source-tag: $SANAPCRAFT_PROJECT_VERSION

apps:
  bandwhich:
    command: bin/bandwhich
    plugs:
    - network
    - network-bind
    - network-control
    - network-status
    - system-observe
    - mount-observe
    - log-observe
